# Generated by Django 4.1 on 2022-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imobil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Gold_Access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultHouse.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
